In [2]:
# imports
import numpy as np

## Create  1D array

In [7]:
# Use numpy.arange¶
# numpy.arange([start, ]stop, [step, ]dtype=None)

one_d = np.arange(1,10)
one_d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Create a 3×3 numpy array of all True’s

In [20]:
nine = np.arange(1,10)
threeXthree = np.reshape(nine, (3,3))
threeXthree_trues = (threeXthree>0)
threeXthree_trues

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Create a 3×3 numpy array of all True’s (2nd method)

In [43]:
threeXthree_trues =  (np.ndarray(shape=(3,3))>0)
threeXthree

## Create a 3×3 numpy array of all True’s (3rd method)

In [49]:
threeXthree_trues = np.full((3,3), True, dtype=bool)
threeXthree_trues

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Create a 3×3 numpy array of all True’s (4th method)

In [66]:
# in Python True is represented as a 1 so np.ones should work too

threeXthree_trues = np.ones((3,3), dtype=bool)
threeXthree_trues

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Extract all odd numbers from arr

In [67]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_mask = (arr % 2 == 1)
arr = arr[odd_mask]
arr

array([1, 3, 5, 7, 9])

# Replace all odd numbers in arr with -1

In [69]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_mask = (arr % 2 == 1)
arr[odd_mask] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Replace all odd numbers in arr with -1 without changing arr

In [93]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# user np.where numpy.where(condition[, x, y])
# When condition is true it yields x otherwise y. 

out = np.where(arr % 2 == 1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [94]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##  Convert a 1D array to a 2D array with 2 rows

In [100]:
arr = np.arange(10)

# use np.reshape where syntax is np.reshape(array,(rows,columns))
# can supply 1 dimension and use -1 to let numpy calculate the other parameter

np.reshape(arr,(2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##  Convert a 1D array to a 2D array with 2 rows (method 2)

In [103]:
# do it in a one liner, using .reshape() method

np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Stack arrays a and b vertically

In [112]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# use vstack supplying tuple of arrays which have the same shape along all but the first axis.

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Stack arrays a and b vertically (2nd method found on [numpy.org](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy-concatenate) )

In [114]:
# use np.concatenate method 

np.concatenate((a,b))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [117]:
# noting the wrong answer
np.concatenate((a,b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Stack the arrays a and b horizontally

In [119]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [122]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 10: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

`a = np.array([1,2,3])`

Desired Output:

> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [124]:
a = np.array([1,2,3])
b = np.repeat(a,3)
np.concatenate((b,a,a,a))

## Create the following pattern without hardcoding. Use only numpy functions and the below input array a. (2nd method)

use np.tile which constructs a new array by repeating array supplied

In [141]:
repeating_as = np.tile(a,3)
repeating_as

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [142]:
np.concatenate((np.repeat(a,3), np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])